apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: arti-test-go
  janus-idp.io/tekton: arti-test-go
  backstage.io/kubernetes-id: arti-test-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: arti-test-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
