apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: arti-test-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: arti-test-go 
  name: arti-test-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: arti-test-go 
